### ISSUE TITLE
Notification content does not support Chinese

### ISSUE THREAD

**Issue by loveqianool** [K0IN/Notify#33]
```
curl -X POST -H "Content-Type: application/json" -d '{"title":"通知", "message":"测试"}' https://notify_app-demo.thisk0in.workers.dev/api/notify
```
Show success but no notification

**Comment by K0IN** [comment]
I fixed the issue (will be merged when tests run successfully)
I will look further into it, some day—since I use encodeURIComponent which will greatly reduce the input length (due to 通知 will be encoded and sent as JUU5JTgwJTlBJUU3JTlGJUE1)
