### ISSUE TITLE
Login action failed: Error: Deno.openKv is not a function

### ISSUE THREAD

**Issue by loveqianool** [K0IN/Notify#84]
![屏幕截图 2023-08-02 200844](https://github.com/K0IN/Notify/assets/739497/f543fba5-d32b-4739-bf8a-d60f7dd34544)

**Comment by K0IN** [comment]
DenoKV is a closed beta feature, which might not be enabled on your account.

To unlock / further information, check [this](https://deno.com/deploy/docs/kv)
