### ISSUE TITLE
borken vapid. borken notifications.

### ISSUE THREAD

**Issue by africa552036012020255252355634346346346** [K0IN/Notify#98]
helo,,,,,,,,,,,,,,,,,,,,,,,,,,

url for generating vapid is borken...

code & api requires 500+ iq to understand, pls fix so u can test send notifications on page easy & fetch list send notifications to specific simplified user ids like phone numbers       :   !!!!

also notofications no work brave web browser if no use google paranoid security settings, pls fix i have many other sites they work

other than that very good i have fork https://github.com/ttttttttttttttttttttttttttttttttttttttx/n

:beers:

**Comment by K0IN** [comment]
Hi, I'm not sure what you mean that the API required 500+ IQ? Can you specific what is confusing for you?
Also, this app is meant for standalone usage, feel free to modify this project however you please. :)
